// Generated by https://quicktype.io

export interface ChildFile {
  id: number;
  name: null;
  children: [];
  content: Content;
  content_page_id: number;
  cover_id: null;
  // (?) always duplicate of content
  data: Content;
  embeddable_item_id: null;
  form: "file";
  is_row: boolean;
  lesson_id: null;
  parent_id: number;
  position: number;
  products: [];
  purpose: number;
  seller_id: null;
  template: boolean | null;
  created_at: Date;
  updated_at: Date;
  goods: Good[];
}

export interface Content {
  list?: null | string;
  width: string;
  radius: string;
  max_width: number | string;
  text_font: string;
  text_size: string;
  text_color: string;
  text_style: string;
  button_font: string;
  button_size: string;
  padding_top: string;
  button_color: string;
  button_style: string;
  padding_left: string;
  transparency: string;
  padding_right: string;
  padding_units: string;
  padding_bottom: string;
  background_color: string;
  button_animation: string;
  button_text_color: string;
  button_view_style: string;
  old_max_width?: number | string;
  cover_id?: string;
  background_image?: null;
}

export interface Good {
  id: number;
  digital: Digital;
}

export interface Digital {
  id: number;
  name: null;
  is_image: boolean;
  is_audio: boolean;
  wistia_data: null;
  file: File;
}

export interface File {
  content_type: string;
  name: string;
  size: number;
  original: string;
  duration: null;
  icon: string;
}
