// Generated by https://quicktype.io

export interface ChildVideo {
  id: number;
  name: null;
  children: [];
  content: Content;
  content_page_id: number;
  cover_id: null;
  // (?) always duplicate of content
  data: Content;
  embeddable_item_id: null;
  form: "video";
  is_row: boolean;
  lesson_id: null;
  parent_id: number;
  position: number;
  products: [];
  purpose: number;
  seller_id: null;
  template: boolean | null;
  created_at: Date;
  updated_at: Date;
  goods: Good[];
}

export interface Content {
  type?: string;
  width: string;
  max_width: string;
  padding_top: string;
  padding_left: string;
  player_color: string;
  transparency: string;
  padding_right: string;
  padding_units: string;
  padding_bottom: string;
  background_color: string;
  playbar_disabled?: boolean;
  horizontal_alignment: string;
  integrations_background: string;
  list?: null | string;
  background_image?: null;
}

export interface Good {
  id: number;
  digital: Digital;
}

export interface Digital {
  id: number;
  name: null | string;
  is_image: boolean;
  is_audio: boolean;
  wistia_data: WistiaData;
  file: File;
}

export interface File {
  content_type: string | null;
  name: null | string;
  size: number | null;
  original: string;
  duration: null;
  icon: string;
}

export interface WistiaData {
  id: number;
  name: string;
  type: string;
  assets: Asset[];
  status: string;
  created: Date;
  project: Project;
  success: boolean;
  updated: Date;
  duration: number;
  progress: number;
  hashed_id: string;
  thumbnail: Thumbnail;
  description: string;
  archived?: boolean;
  embedCode?: string;
}

export interface Asset {
  url: string;
  type: string;
  width: number;
  height: number;
  fileSize: number;
  contentType: string;
}

export interface Project {
  id: number;
  name: string;
  hashed_id: string;
}

export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}
