// Generated by https://quicktype.io

export interface ChildText {
  id: number;
  name: null;
  children: [];
  content: Content;
  content_page_id: number;
  cover_id: null;
  // (?) always duplicate of content
  data: Content;
  embeddable_item_id: null;
  form: "text";
  is_row: boolean;
  lesson_id: null;
  parent_id: number;
  position: number;
  products: [];
  purpose: number;
  seller_id: null;
  template: boolean | null;
  created_at: Date;
  updated_at: Date;
  goods: [];
}

export interface Content {
  list: null | string;
  text: string;
  width: string;
  max_width: string;
  padding_top: string;
  padding_left: string;
  transparency: string;
  padding_right: string;
  padding_units: string;
  padding_bottom: string;
  background_color: string;
  background_image?: null;
}
