// Generated by https://quicktype.io

export interface ChildPicture {
  id: number;
  name: null;
  children: [];
  content: Content;
  content_page_id: number;
  cover_id: number;
  // (?) always duplicate of content
  data: Content;
  embeddable_item_id: null;
  form: "picture";
  is_row: boolean;
  lesson_id: null;
  parent_id: number;
  position: number;
  products: [];
  purpose: number;
  seller_id: null;
  template: boolean;
  created_at: Date;
  updated_at: Date;
  cover: Cover;
  goods: Good[];
}

export interface Content {
  list: null | string;
  width: string;
  max_width: string;
  padding_top: string;
  padding_left: string;
  padding_right: string;
  padding_units: string;
  original_width: string;
  padding_bottom: string;
  original_height: string;
  background_color: string;
  vertical_alignment: string;
  horizontal_alignment: string;
  background_image?: string;
}

export interface Cover {
  id: number;
  cover: string;
  file: CoverFile;
  file_content_type: null;
  file_crop_h: number;
  file_crop_w: number;
  file_crop_x: number;
  file_crop_y: number;
  file_file_name: null;
  file_file_size: null;
  file_name: null;
  file_remote_url: null;
  file_updated_at: null;
  link: null;
  ownerable_id: number;
  ownerable_type: string;
  thumb: string;
  type: string;
  uploaded_via_te: null;
  url: string;
  uuid: string;
  video_link: null;
  voucher_template: boolean;
  created_at: Date;
  updated_at: Date;
}

export interface CoverFile {
  s_100: string;
  s_640: string;
  s_1200: string;
  custom: string;
  original: string;
  name: string;
  cdn_url: string;
  download_url: string;
  size: number;
  content_type: string;
}

export interface Good {
  id: number;
  digital: Digital;
}

export interface Digital {
  id: number;
  name: string;
  is_image: boolean;
  is_audio: boolean;
  wistia_data: WistiaData;
  file: DigitalFile;
}

export interface DigitalFile {
  content_type: string;
  icon: string;
  name: string;
  size: number;
  duration: number;
}

export interface WistiaData {
}
