// Generated by https://quicktype.io

import type { ErrorResponse } from "./common.ts";

export type LessonsResponse = ErrorResponse | Lessons;

export interface Lessons {
  success: true;
  data: Data;
}

export interface Data {
  total_count: number;
  list: List[];
}

export interface List {
  id: number;
  name: string;
  active: boolean;
  allow_lesson_reset: boolean;
  comments_allowed: boolean;
  content_page_after_id: null;
  content_page_before_id: number | null;
  content_page_id: number | null;
  duration: null;
  duration_type: string;
  end_date: null;
  fb_comments_allowed: boolean;
  fb_url: string;
  is_category: boolean;
  lesson_settings: LessonSettings;
  next_lesson_id: number | null;
  overview: boolean;
  parent_id: number | null;
  position: number;
  prev_lesson_id: number | null;
  preview: boolean | null;
  product_id: number;
  publish_at: null;
  publish_date: string;
  publish_in: null;
  publish_in_time: boolean;
  publish_time_zone: null | string;
  quiz_enabled: null;
  quiz_id: null;
  static: boolean;
  with_duration: boolean;
  created_at: Date;
  updated_at: Date;
  nesting_level: number;
}

export interface LessonSettings {
}
